const MONTHS=["Wrzesień","Październik","Listopad","Grudzień","Styczeń","Luty","Marzec","Kwiecień","Maj","Czerwiec","Lipiec","Sierpień"],KEY="rw_v43";
const SETTINGS={schools:["SP 162","ZSP 17"],workshops:["Rękodzieło","Zaawansowane","Artystyczne"],classes:["1A","1B","2A","2B","3A","3B","4A","4B","5A","5B","6A","6B","7A","7B","8A","8B"],clubs:["Tak","Nie"],genders:["Dziewczynka","Chłopiec"],days:["Poniedziałek","Wtorek","Środa","Czwartek","Piątek"],times:["13:30","14:00","14:30","15:00","15:30","16:00"],incomeCategories:["Warsztaty jednorazowe","Impreza","Sprzedaż rękodzieła","Dodatkowe zajęcia","Inne"]};
const DEMO={settings:SETTINGS,children:[
{id:"c1",lastName:"Kolasa",firstName:"Nikola",gender:"Dziewczynka",school:"SP 162",className:"4A",club:"Tak",parent:"Rodzic testowy",phone:"",email:"",notes:""},
{id:"c2",lastName:"Nowak",firstName:"Maja",gender:"Dziewczynka",school:"SP 162",className:"3B",club:"Tak",parent:"Rodzic testowy 2",phone:"",email:"",notes:""},
{id:"c3",lastName:"Kowalski",firstName:"Jan",gender:"Chłopiec",school:"ZSP 17",className:"5A",club:"Nie",parent:"Rodzic testowy 3",phone:"",email:"",notes:""}],
enrollments:[
{id:"e1",childId:"c1",workshop:"Rękodzieło",day:"Wtorek",time:"15:00",school:"SP 162",regularPrice:155,billingStatus:"Płatne",discountMode:"none",customDiscount:0,customPrice:0,priceNote:""},
{id:"e2",childId:"c1",workshop:"Zaawansowane",day:"Środa",time:"15:30",school:"SP 162",regularPrice:165,billingStatus:"Płatne",discountMode:"10",customDiscount:0,customPrice:0,priceNote:"2. zajęcia"},
{id:"e3",childId:"c2",workshop:"Artystyczne",day:"Wtorek",time:"15:00",school:"SP 162",regularPrice:145,billingStatus:"Bezpłatne",discountMode:"none",customDiscount:0,customPrice:0,priceNote:"miejsce bezpłatne"},
{id:"e4",childId:"c3",workshop:"Rękodzieło",day:"Czwartek",time:"14:30",school:"ZSP 17",regularPrice:155,billingStatus:"Płatne",discountMode:"none",customDiscount:0,customPrice:0,priceNote:""}],
payments:[{id:"p1",childId:"c1",enrollmentId:"e1",month:"Wrzesień",amount:155,date:"2026-09-02",title:"test"}],
manualStatuses:[],incomes:[{id:"i1",date:"2026-07-10",month:"Lipiec",category:"Warsztaty jednorazowe",amount:300,description:"Przychód testowy",notes:""}]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const clone=o=>JSON.parse(JSON.stringify(o));
let db=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||clone(DEMO)}catch{return clone(DEMO)}})();
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function esc(x=""){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function money(n){return Number(n||0).toLocaleString("pl-PL",{style:"currency",currency:"PLN"})}
function price(e){if(["Bezpłatne","Charytatywne"].includes(e.billingStatus))return 0;if(e.billingStatus==="Indywidualna cena")return Number(e.customPrice||0);let d=e.discountMode==="custom"?Number(e.customDiscount||0):Number(e.discountMode||0);return Number(e.regularPrice||0)*(1-d/100)}
function paid(eid,m){return db.payments.filter(p=>p.enrollmentId===eid&&p.month===m).reduce((s,p)=>s+Number(p.amount||0),0)}
function manual(eid,m){return db.manualStatuses.find(x=>x.enrollmentId===eid&&x.month===m)}
function status(e,m){if(["Bezpłatne","Charytatywne"].includes(e.billingStatus))return "free";let x=manual(e.id,m);if(x?.status)return x.status;return paid(e.id,m)>=price(e)?"paid":"unpaid"}
function statusLabel(e,m){let s=status(e,m);return s==="paid"?"WPŁACONO":s==="free"?e.billingStatus.toUpperCase():"BRAK WPŁATY"}
function childEnrollments(id){return db.enrollments.filter(e=>e.childId===id)}
function dueChild(id,m){return childEnrollments(id).reduce((s,e)=>s+(status(e,m)==="free"?0:price(e)),0)}
function paidChild(id,m){return childEnrollments(id).reduce((s,e)=>s+paid(e.id,m),0)}
function fillMonths(){["dashMonth","paymentMonth","incomeMonth","paymentDialogMonth","incomeDialogMonth"].forEach(id=>{$("#"+id).innerHTML=MONTHS.map(m=>`<option>${m}</option>`).join("")});$("#dashMonth").value=$("#paymentMonth").value="Wrzesień";$("#incomeMonth").value="Lipiec"}
function fillSettingSelects(){$$("[data-setting]").forEach(s=>{let v=s.value,key=s.dataset.setting;s.innerHTML='<option value="">— wybierz —</option>'+db.settings[key].map(x=>`<option>${esc(x)}</option>`).join("");s.value=v})}
function setFilter(sel,vals,label){let v=sel.value;sel.innerHTML=`<option value="">${label}</option>`+[...new Set(vals.filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pl")).map(x=>`<option>${esc(x)}</option>`).join("");sel.value=v}
function refreshFilters(){setFilter($("#dashSchool"),db.children.map(c=>c.school),"Wszystkie szkoły");setFilter($("#childSchool"),db.children.map(c=>c.school),"Wszystkie szkoły");setFilter($("#groupSchool"),db.enrollments.map(e=>e.school),"Wszystkie szkoły");setFilter($("#groupDay"),db.enrollments.map(e=>e.day),"Wszystkie dni");setFilter($("#groupTime"),db.enrollments.map(e=>e.time),"Wszystkie godziny");setFilter($("#incomeCategory"),db.incomes.map(i=>i.category),"Wszystkie kategorie")}
function render(){fillSettingSelects();refreshFilters();renderDashboard();renderChildren();renderPayments();renderIncome();renderGroups();renderReports();renderSettings()}
function renderDashboard(){let m=$("#dashMonth").value,school=$("#dashSchool").value,cs=db.children.filter(c=>!school||c.school===school),ids=new Set(cs.map(c=>c.id)),es=db.enrollments.filter(e=>ids.has(e.childId)),due=es.reduce((s,e)=>s+(status(e,m)==="free"?0:price(e)),0),pay=es.reduce((s,e)=>s+paid(e.id,m),0),extra=db.incomes.filter(i=>i.month===m).reduce((s,i)=>s+Number(i.amount||0),0);
$("#stats").innerHTML=[["Dzieci",cs.length],["Dziewczynki",cs.filter(c=>c.gender==="Dziewczynka").length],["Chłopcy",cs.filter(c=>c.gender==="Chłopiec").length],["Zapisy",es.length],["Wpłacono",money(pay)],["Brak wpłaty",es.filter(e=>status(e,m)==="unpaid").length]].map(x=>`<div class=stat><b>${x[1]}</b><span>${x[0]}</span></div>`).join("");
$("#monthTitle").textContent=m;
$("#moneyTiles").innerHTML=[["Należne",money(due),""],["Wpłaty dzieci",money(pay),""],["Dodatkowe przychody",money(extra),""],["Razem wpływy",money(pay+extra),"total"]].map(x=>`<div class="moneyTile ${x[2]}"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("");
let ar=cs.map(c=>({c,missing:Math.max(0,dueChild(c.id,m)-paidChild(c.id,m))})).filter(x=>x.missing>0);$("#arrearsList").innerHTML=ar.map(x=>`<div class=arrearRow><span><b>${esc(x.c.lastName)} ${esc(x.c.firstName)}</b><br><span class=meta>${esc(x.c.parent||"")}</span></span><strong class="statusText unpaid">${money(x.missing)}</strong></div>`).join("")||'<div class=meta>Brak zaległości.</div>'}
function enrollCard(e,m=$("#dashMonth").value){let st=status(e,m);return `<div class=enrollment><div class=itemTop><div><b>${esc(e.workshop)}</b><div class=meta>${esc(e.day)} ${esc(e.time)} • ${esc(e.school)}<br>Cena ${money(price(e))}${e.discountMode!=="none"&&e.billingStatus==="Płatne"?` • rabat ${e.discountMode==="custom"?e.customDiscount:e.discountMode}%`:""}${e.priceNote?` • ${esc(e.priceNote)}`:""}</div></div><span class="statusText ${st==="paid"?"paid":st==="free"?"free":"unpaid"}">${statusLabel(e,m)}</span></div><button class="ghost mini editEnrollment" data-id="${e.id}">Edytuj zajęcia</button></div>`}
function childCard(c){let m=$("#dashMonth").value;return `<div class=item><div class=itemTop><div><h4>${esc(c.lastName)} ${esc(c.firstName)}</h4><div class=meta>${esc(c.className)} • ${esc(c.school)} • świetlica: ${esc(c.club)} • ${esc(c.gender)}</div><div class=meta><b>Do zapłaty ${m}: ${money(dueChild(c.id,m))}</b></div></div><button class="ghost mini profileBtn" data-id="${c.id}">Profil</button></div><div class=enrollments>${childEnrollments(c.id).map(e=>enrollCard(e)).join("")||'<div class=meta>Brak zajęć.</div>'}</div><button class="primary mini addEnrollment" data-child="${c.id}">+ Dodaj zajęcia</button></div>`}
function bindChildren(){$$(".profileBtn").forEach(b=>b.onclick=()=>openProfile(b.dataset.id));$$(".addEnrollment").forEach(b=>b.onclick=()=>openEnrollment(null,b.dataset.child));$$(".editEnrollment").forEach(b=>b.onclick=()=>openEnrollment(b.dataset.id))}
function renderChildren(){let q=$("#childSearch").value.toLowerCase(),s=$("#childSchool").value,a=db.children.filter(c=>(c.lastName+" "+c.firstName).toLowerCase().includes(q)&&(!s||c.school===s)).sort((a,b)=>a.lastName.localeCompare(b.lastName,"pl"));$("#childrenList").innerHTML=a.map(childCard).join("")||'<div class=item>Brak wyników.</div>';bindChildren()}
function renderPayments(){let m=$("#paymentMonth").value,q=$("#paymentSearch").value.toLowerCase(),html="";db.children.filter(c=>(c.lastName+" "+c.firstName+" "+c.parent).toLowerCase().includes(q)).sort((a,b)=>a.lastName.localeCompare(b.lastName,"pl")).forEach(c=>{html+=`<div class=item><h4>${esc(c.lastName)} ${esc(c.firstName)}</h4><div class=meta>Należne ${money(dueChild(c.id,m))} • wpłacono ${money(paidChild(c.id,m))}</div>${childEnrollments(c.id).map(e=>{let st=status(e,m);return `<div class=enrollment><div class=itemTop><div><b>${esc(e.workshop)}</b><div class=meta>Należne ${money(price(e))} • wpłaty ${money(paid(e.id,m))}</div></div><span class="statusText ${st==="paid"?"paid":st==="free"?"free":"unpaid"}">${statusLabel(e,m)}</span></div><button class="ghost mini manualStatus" data-e="${e.id}" data-m="${m}">Korekta statusu</button>${db.payments.filter(p=>p.enrollmentId===e.id&&p.month===m).map(p=>`<button class="ghost mini editPayment" data-id="${p.id}">Edytuj ${money(p.amount)}</button><button class="danger mini deletePayment" data-id="${p.id}">Usuń</button>`).join("")}</div>`}).join("")}</div>`});$("#paymentsList").innerHTML=html||'<div class=item>Brak wyników.</div>';$$(".manualStatus").forEach(b=>b.onclick=()=>openManual(b.dataset.e,b.dataset.m));$$(".editPayment").forEach(b=>b.onclick=()=>openPayment(b.dataset.id));$$(".deletePayment").forEach(b=>b.onclick=()=>{if(confirm("Usunąć wpłatę?")){db.payments=db.payments.filter(p=>p.id!==b.dataset.id);save()}})}
function renderIncome(){let m=$("#incomeMonth").value,cat=$("#incomeCategory").value,a=db.incomes.filter(i=>i.month===m&&(!cat||i.category===cat));$("#incomeList").innerHTML=a.map(i=>`<div class=item><div class=itemTop><div><h4>${money(i.amount)} • ${esc(i.category)}</h4><div class=meta>${esc(i.date)} • ${esc(i.description)}</div></div><button class="danger mini deleteIncome" data-id="${i.id}">Usuń</button></div></div>`).join("")||'<div class=item>Brak przychodów.</div>';$$(".deleteIncome").forEach(b=>b.onclick=()=>{if(confirm("Usunąć?")){db.incomes=db.incomes.filter(i=>i.id!==b.dataset.id);save()}})}
function groupRows(){let s=$("#groupSchool").value,d=$("#groupDay").value,t=$("#groupTime").value;return db.enrollments.filter(e=>(!s||e.school===s)&&(!d||e.day===d)&&(!t||e.time===t)).map(e=>({e,c:db.children.find(c=>c.id===e.childId)})).filter(x=>x.c).sort((a,b)=>a.c.lastName.localeCompare(b.c.lastName,"pl"))}
function renderGroups(){let rows=groupRows();$("#groupsList").innerHTML=rows.map(({c,e})=>`<div class=item><div class=screenOnly><h4>${esc(c.lastName)} ${esc(c.firstName)}</h4><div class=meta>${esc(c.className)} • świetlica: ${esc(c.club)} • ${esc(e.workshop)} • ${esc(e.day)} ${esc(e.time)} • ${esc(e.school)}</div></div><div class=printRow style="display:none"><span>${esc(c.lastName)}</span><span>${esc(c.firstName)}</span><span>${esc(c.className)}</span><span>${esc(c.club)}</span><span>${esc(e.workshop)}</span><span>${esc(e.day)}</span><span>${esc(e.time)}</span><span>${esc(e.school)}</span></div></div>`).join("")||'<div class=item>Brak osób.</div>';$("#printHeader").innerHTML=`<h2>Lista uczestników</h2><p>${esc($("#groupSchool").value||"Wszystkie szkoły")} • ${esc($("#groupDay").value||"wszystkie dni")} • ${esc($("#groupTime").value||"wszystkie godziny")} • liczba: ${rows.length}</p><div class=printRow><b>Nazwisko</b><b>Imię</b><b>Klasa</b><b>Świetlica</b><b>Rodzaj zajęć</b><b>Dzień</b><b>Godzina</b><b>Szkoła</b></div>`}
function renderReports(){let rows=MONTHS.map(m=>{let due=db.enrollments.reduce((s,e)=>s+(status(e,m)==="free"?0:price(e)),0),p=db.payments.filter(x=>x.month===m).reduce((s,x)=>s+Number(x.amount||0),0),i=db.incomes.filter(x=>x.month===m).reduce((s,x)=>s+Number(x.amount||0),0);return [m,due,p,Math.max(0,due-p),i,p+i]});$("#yearReport").innerHTML=`<table class=table><tr><th>Miesiąc</th><th>Należne</th><th>Wpłaty</th><th>Zaległe</th><th>Dodatkowe</th><th>Razem</th></tr>${rows.map(r=>`<tr><td>${r[0]}</td><td>${money(r[1])}</td><td>${money(r[2])}</td><td>${money(r[3])}</td><td>${money(r[4])}</td><td><b>${money(r[5])}</b></td></tr>`).join("")}</table>`;let w={};db.enrollments.forEach(e=>w[e.workshop]=(w[e.workshop]||0)+1);$("#workshopReport").innerHTML=`<table class=table>${Object.entries(w).map(([k,v])=>`<tr><td>${esc(k)}</td><th>${v}</th></tr>`).join("")}</table>`}
const settingNames={schools:"Szkoły",workshops:"Rodzaje zajęć",classes:"Klasy",clubs:"Świetlica",genders:"Płeć",days:"Dni",times:"Godziny",incomeCategories:"Kategorie przychodów"};
function renderSettings(){$("#settingsLists").innerHTML=Object.entries(settingNames).map(([k,n])=>`<div class=settingBox><h3>${n}</h3><div class=settingTags>${db.settings[k].map((x,i)=>`<span class=settingTag>${esc(x)} <button class="danger mini delSetting" data-k="${k}" data-i="${i}">×</button></span>`).join("")}</div><div class=addSetting><input data-new="${k}" placeholder="Dodaj pozycję"><button class="primary addSetting" data-k="${k}">Dodaj</button></div></div>`).join("");$$(".addSetting").forEach(b=>b.onclick=()=>{let i=$(`[data-new="${b.dataset.k}"]`),v=i.value.trim();if(v){db.settings[b.dataset.k].push(v);save()}});$$(".delSetting").forEach(b=>b.onclick=()=>{db.settings[b.dataset.k].splice(+b.dataset.i,1);save()})}
function openProfile(id){let c=db.children.find(x=>x.id===id);if(!c)return;let es=childEnrollments(id);$("#profileContent").innerHTML=`<small>PROFIL DZIECKA</small><h3 class=profileTitle>${esc(c.lastName)} ${esc(c.firstName)}</h3><div class=profileGrid><div class=profileBox><span>Klasa</span><b>${esc(c.className)}</b></div><div class=profileBox><span>Szkoła</span><b>${esc(c.school)}</b></div><div class=profileBox><span>Świetlica</span><b>${esc(c.club)}</b></div><div class=profileBox><span>Rodzic</span><b>${esc(c.parent||"—")}</b></div><div class=profileBox><span>Telefon</span><b>${esc(c.phone||"—")}</b></div><div class=profileBox><span>E-mail</span><b>${esc(c.email||"—")}</b></div></div><h3>Zajęcia i historia wpłat</h3>${es.map(e=>`<div class=enrollment><div class=itemTop><b>${esc(e.workshop)}</b><span class="statusText ${status(e,$("#dashMonth").value)==="paid"?"paid":status(e,$("#dashMonth").value)==="free"?"free":"unpaid"}">${statusLabel(e,$("#dashMonth").value)}</span></div><div class=meta>${esc(e.day)} ${esc(e.time)} • ${money(price(e))}</div><table class=table>${MONTHS.map(m=>`<tr><td>${m}</td><td>${money(paid(e.id,m))}</td><td><span class="statusText ${status(e,m)==="paid"?"paid":status(e,m)==="free"?"free":"unpaid"}">${statusLabel(e,m)}</span></td></tr>`).join("")}</table></div>`).join("")}`;$("#profileDialog").showModal()}
function openChild(id){let c=db.children.find(x=>x.id===id)||{};fillSettingSelects();let f=$("#childForm");[...f.elements].forEach(el=>{if(el.name)el.value=c[el.name]||""});$("#childDialog").showModal()}
function openEnrollment(id,childId){fillSettingSelects();let e=db.enrollments.find(x=>x.id===id)||{childId,billingStatus:"Płatne",discountMode:"none"};let f=$("#enrollmentForm");[...f.elements].forEach(el=>{if(el.name)el.value=e[el.name]??""});$("#enrollmentDialog").showModal()}
function populatePaymentChildren(q="",selected=""){let a=db.children.filter(c=>(c.lastName+" "+c.firstName).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>a.lastName.localeCompare(b.lastName,"pl"));$("#paymentChild").innerHTML=a.map(c=>`<option value="${c.id}">${esc(c.lastName)} ${esc(c.firstName)}</option>`).join("");if(selected)$("#paymentChild").value=selected;populatePaymentEnrollments()}
function populatePaymentEnrollments(selected=""){let id=$("#paymentChild").value;$("#paymentEnrollment").innerHTML=childEnrollments(id).map(e=>`<option value="${e.id}">${esc(e.workshop)} • ${esc(e.day)} ${esc(e.time)} • ${money(price(e))}</option>`).join("");if(selected)$("#paymentEnrollment").value=selected}
function openPayment(id){let p=db.payments.find(x=>x.id===id)||{month:$("#paymentMonth").value,date:new Date().toISOString().slice(0,10)};$("#paymentForm").reset();$("#paymentForm [name=id]").value=p.id||"";populatePaymentChildren("",p.childId);if(p.childId){$("#paymentChild").value=p.childId;populatePaymentEnrollments(p.enrollmentId)}$("#paymentDialogMonth").value=p.month;$("#paymentForm [name=amount]").value=p.amount||"";$("#paymentForm [name=date]").value=p.date||"";$("#paymentForm [name=title]").value=p.title||"";$("#paymentDialog").showModal()}
function openManual(eid,m){let x=manual(eid,m)||{};let f=$("#manualStatusForm");f.enrollmentId.value=eid;f.month.value=m;f.status.value=x.status||"";f.note.value=x.note||"";$("#manualStatusDialog").showModal()}
function openIncome(){fillSettingSelects();$("#incomeForm").reset();$("#incomeDialogMonth").value=$("#incomeMonth").value;$("#incomeDialog").showModal()}
$("#saveChild").onclick=e=>{e.preventDefault();let o=Object.fromEntries(new FormData($("#childForm")));if(o.id)Object.assign(db.children.find(x=>x.id===o.id),o);else{o.id="c"+Date.now();db.children.push(o)}save();$("#childDialog").close()}
$("#saveEnrollment").onclick=e=>{e.preventDefault();let o=Object.fromEntries(new FormData($("#enrollmentForm")));o.regularPrice=+o.regularPrice||0;o.customDiscount=+o.customDiscount||0;o.customPrice=+o.customPrice||0;if(o.id)Object.assign(db.enrollments.find(x=>x.id===o.id),o);else{o.id="e"+Date.now();db.enrollments.push(o)}save();$("#enrollmentDialog").close()}
$("#savePayment").onclick=e=>{e.preventDefault();let o=Object.fromEntries(new FormData($("#paymentForm")));o.amount=+o.amount||0;if(o.id)Object.assign(db.payments.find(x=>x.id===o.id),o);else{o.id="p"+Date.now();db.payments.push(o)}save();$("#paymentDialog").close()}
$("#saveManualStatus").onclick=e=>{e.preventDefault();let o=Object.fromEntries(new FormData($("#manualStatusForm")));db.manualStatuses=db.manualStatuses.filter(x=>!(x.enrollmentId===o.enrollmentId&&x.month===o.month));if(o.status)db.manualStatuses.push({...o,id:"m"+Date.now()});save();$("#manualStatusDialog").close()}
$("#saveIncome").onclick=e=>{e.preventDefault();let o=Object.fromEntries(new FormData($("#incomeForm")));o.amount=+o.amount||0;o.id="i"+Date.now();db.incomes.push(o);save();$("#incomeDialog").close()}
$("#addChildBtn").onclick=()=>openChild();$("#addPaymentBtn").onclick=()=>openPayment();$("#addIncomeBtn").onclick=openIncome;$("#paymentChildSearch").oninput=e=>populatePaymentChildren(e.target.value);$("#paymentChild").onchange=()=>populatePaymentEnrollments();
$("#quickSearch").oninput=e=>{let q=e.target.value.trim().toLowerCase();let a=q?db.children.filter(c=>c.lastName.toLowerCase().startsWith(q)||(`${c.lastName} ${c.firstName}`).toLowerCase().startsWith(q)).slice(0,8):[];$("#quickResults").innerHTML=a.map(c=>`<button class=quickCard data-profile="${c.id}"><b>${esc(c.lastName)} ${esc(c.firstName)}</b><div class=meta>${esc(c.className)} • ${esc(c.school)} • zajęcia: ${childEnrollments(c.id).length}</div><div class=tap>Kliknij, aby otworzyć profil</div></button>`).join("");$$("[data-profile]").forEach(b=>b.onclick=()=>openProfile(b.dataset.profile))}
$("#childSearch").oninput=renderChildren;$("#childSchool").onchange=renderChildren;$("#paymentSearch").oninput=renderPayments;$("#paymentMonth").onchange=renderPayments;$("#incomeMonth").onchange=renderIncome;$("#incomeCategory").onchange=renderIncome;$("#dashMonth").onchange=renderDashboard;$("#dashSchool").onchange=renderDashboard;["groupSchool","groupDay","groupTime"].forEach(id=>$("#"+id).onchange=renderGroups);$("#printGroup").onclick=()=>print();
function download(n,t,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type}));a.download=n;a.click()}
$("#backupBtn").onclick=$("#exportJson").onclick=()=>download("rozliczenia-v43.json",JSON.stringify(db,null,2),"application/json");
$("#exportCsv").onclick=()=>{let h=["Nazwisko","Imię","Klasa","Świetlica","Rodzaj zajęć","Dzień","Godzina","Szkoła",...MONTHS],r=db.enrollments.map(e=>{let c=db.children.find(x=>x.id===e.childId);return[c.lastName,c.firstName,c.className,c.club,e.workshop,e.day,e.time,e.school,...MONTHS.map(m=>paid(e.id,m))]});download("rozliczenia-v43.csv",[h,...r].map(x=>x.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv;charset=utf-8")}
function parseCSV(t){let rows=[],r=[],c="",q=false;for(let i=0;i<t.length;i++){let x=t[i],n=t[i+1];if(x=='"'&&q&&n=='"'){c+='"';i++}else if(x=='"')q=!q;else if(x==","&&!q){r.push(c);c=""}else if((x=="\n"||x=="\r")&&!q){if(x=="\r"&&n=="\n")i++;r.push(c);c="";if(r.some(v=>v))rows.push(r);r=[]}else c+=x}if(c||r.length){r.push(c);rows.push(r)}return rows}
$("#parseForm").onclick=()=>{let rows=parseCSV($("#formPaste").value.trim());if(rows.length<2)return alert("Brak danych.");$("#formPreview").innerHTML=`<div class=item>Rozpoznano ${rows.length-1} zgłoszeń. Import szczegółowy pozostaje do dalszej optymalizacji.</div>`}
$$("[data-go]").forEach(b=>b.onclick=()=>{$$(".view").forEach(v=>v.classList.toggle("active",v.dataset.view===b.dataset.go));$$("[data-go]").forEach(x=>x.classList.toggle("active",x===b));scrollTo(0,0)})
fillMonths();render();