const MONTHS=["Wrzesień","Październik","Listopad","Grudzień","Styczeń","Luty","Marzec","Kwiecień","Maj","Czerwiec","Lipiec","Sierpień"],KEY="rw_v4";
const baseSettings={schools:["SP 162","ZSP 17"],workshops:["Rękodzieło","Zaawansowane","Artystyczne"],classes:["1A","1B","2A","2B","3A","3B","4A","4B","5A","5B","6A","6B","7A","7B","8A","8B"],clubs:["Tak","Nie"],genders:["Dziewczynka","Chłopiec"],days:["Poniedziałek","Wtorek","Środa","Czwartek","Piątek"],times:["13:30","14:00","14:30","15:00","15:30","16:00"],incomeCategories:["Warsztaty jednorazowe","Impreza","Sprzedaż rękodzieła","Dodatkowe zajęcia","Inne"]};
const demo={settings:baseSettings,payers:[
{id:"r1",name:"Rodzina Kolasa",parent:"Rodzic testowy",phone:"",email:""},
{id:"r2",name:"Rodzina Nowak",parent:"Rodzic testowy 2",phone:"",email:""}
],children:[
{id:"c1",lastName:"Kolasa",firstName:"Nikola",gender:"Dziewczynka",school:"SP 162",className:"4A",club:"Tak",activeStatus:"Aktywny",payerId:"r1",parent:"Rodzic testowy",phone:"",email:"",notes:""},
{id:"c2",lastName:"Nowak",firstName:"Maja",gender:"Dziewczynka",school:"SP 162",className:"3B",club:"Tak",activeStatus:"Aktywny",payerId:"r2",parent:"Rodzic testowy 2",phone:"",email:"",notes:""},
{id:"c3",lastName:"Kowalski",firstName:"Jan",gender:"Chłopiec",school:"ZSP 17",className:"5A",club:"Nie",activeStatus:"Aktywny",payerId:"",parent:"Rodzic testowy 3",phone:"",email:"",notes:""}],
enrollments:[
{id:"e1",childId:"c1",workshop:"Rękodzieło",day:"Wtorek",time:"15:00",school:"SP 162",regularPrice:155,billingStatus:"Płatne",discountMode:"none",customDiscount:0,customPrice:0,priceNote:""},
{id:"e2",childId:"c1",workshop:"Zaawansowane",day:"Środa",time:"15:30",school:"SP 162",regularPrice:165,billingStatus:"Płatne",discountMode:"10",customDiscount:0,customPrice:0,priceNote:"2. zajęcia"},
{id:"e3",childId:"c2",workshop:"Artystyczne",day:"Wtorek",time:"15:00",school:"SP 162",regularPrice:145,billingStatus:"Bezpłatne",discountMode:"none",customDiscount:0,customPrice:0,priceNote:"miejsce bezpłatne"},
{id:"e4",childId:"c3",workshop:"Rękodzieło",day:"Czwartek",time:"14:30",school:"ZSP 17",regularPrice:155,billingStatus:"Płatne",discountMode:"none",customDiscount:0,customPrice:0,priceNote:""}],
payments:[{id:"p1",childId:"c1",enrollmentId:"e1",month:"Wrzesień",amount:155,date:"2026-09-02",title:"test"}],
manualStatuses:[],incomes:[{id:"i1",date:"2026-07-10",month:"Lipiec",category:"Warsztaty jednorazowe",amount:300,description:"Przychód testowy",notes:""}],
attendance:[],applications:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const clone=o=>JSON.parse(JSON.stringify(o));let db=(()=>{try{let x=JSON.parse(localStorage.getItem(KEY));return x||clone(demo)}catch{return clone(demo)}})();
for(const k of ["payers","attendance","applications"]) if(!db[k]) db[k]=[];
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function esc(x=""){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function money(n){return Number(n||0).toLocaleString("pl-PL",{style:"currency",currency:"PLN"})}
function price(e){if(["Bezpłatne","Charytatywne"].includes(e.billingStatus))return 0;if(e.billingStatus==="Indywidualna cena")return Number(e.customPrice||0);let d=e.discountMode==="custom"?Number(e.customDiscount||0):Number(e.discountMode||0);return Math.max(0,Number(e.regularPrice||0)*(1-d/100))}
function paid(eid,m){return db.payments.filter(p=>p.enrollmentId===eid&&p.month===m).reduce((s,p)=>s+Number(p.amount||0),0)}
function manual(eid,m){return db.manualStatuses.find(x=>x.enrollmentId===eid&&x.month===m)}
function status(e,m){if(["Bezpłatne","Charytatywne"].includes(e.billingStatus))return "free";let x=manual(e.id,m);if(x?.status)return x.status;return paid(e.id,m)>=price(e)?"paid":"unpaid"}
function statusLabel(e,m){let s=status(e,m);return s==="paid"?"WPŁACONO":s==="free"?e.billingStatus.toUpperCase():"BRAK WPŁATY"}
function dueChild(childId,m){return db.enrollments.filter(e=>e.childId===childId).reduce((s,e)=>s+(status(e,m)==="free"?0:price(e)),0)}
function paidChild(childId,m){return db.enrollments.filter(e=>e.childId===childId).reduce((s,e)=>s+paid(e.id,m),0)}
function fillMonths(){["dashMonth","paymentMonth","incomeMonth","paymentDialogMonth","incomeDialogMonth"].forEach(id=>{$("#"+id).innerHTML=MONTHS.map(x=>`<option>${x}</option>`).join("")});$("#dashMonth").value=$("#paymentMonth").value="Wrzesień";$("#incomeMonth").value="Lipiec"}
function optionsFromSettings(){ $$("[data-setting]").forEach(s=>{let v=s.value,key=s.dataset.setting;s.innerHTML='<option value="">— wybierz —</option>'+db.settings[key].map(x=>`<option>${esc(x)}</option>`).join("");s.value=v})}
function childEnrollments(id){return db.enrollments.filter(e=>e.childId===id)}
function refreshFilters(){let set=(sel,vals,label)=>{let v=sel.value;sel.innerHTML=`<option value="">${label}</option>`+[...new Set(vals.filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pl")).map(x=>`<option>${esc(x)}</option>`).join("");sel.value=v};set($("#dashSchool"),db.children.map(c=>c.school),"Wszystkie szkoły");set($("#childSchool"),db.children.map(c=>c.school),"Wszystkie szkoły");set($("#groupSchool"),db.enrollments.map(e=>e.school),"Wszystkie szkoły");set($("#groupDay"),db.enrollments.map(e=>e.day),"Wszystkie dni");set($("#groupTime"),db.enrollments.map(e=>e.time),"Wszystkie godziny");set($("#incomeCategory"),db.incomes.map(i=>i.category),"Wszystkie kategorie")}
function render(){optionsFromSettings();refreshFilters();renderDashboard();renderChildren();renderPayments();renderIncome();renderGroups();renderReports();renderSettings();renderApplications()}
function renderDashboard(){let m=$("#dashMonth").value,school=$("#dashSchool").value,cs=db.children.filter(c=>(c.activeStatus||"Aktywny")==="Aktywny"&&(!school||c.school===school)),ids=new Set(cs.map(c=>c.id)),es=db.enrollments.filter(e=>ids.has(e.childId));let incomePayments=es.reduce((s,e)=>s+paid(e.id,m),0),due=es.reduce((s,e)=>s+(status(e,m)==="free"?0:price(e)),0),extra=db.incomes.filter(i=>i.month===m).reduce((s,i)=>s+Number(i.amount||0),0),unpaid=es.filter(e=>status(e,m)==="unpaid").length;$("#stats").innerHTML=[["Dzieci",cs.length],["Dziewczynki",cs.filter(c=>c.gender==="Dziewczynka").length],["Chłopcy",cs.filter(c=>c.gender==="Chłopiec").length],["Należne",money(due)],["Wpłacono",money(incomePayments)],["Zaległe zapisy",unpaid]].map(x=>`<div class=stat><b>${x[1]}</b><span>${x[0]}</span></div>`).join("");$("#dashSummary").innerHTML=`<p><b>${m}</b>: należne ${money(due)} • wpłaty dzieci ${money(incomePayments)} • dodatkowe przychody ${money(extra)} • razem wpływy ${money(incomePayments+extra)}</p>`;let arrears=[];for(const c of cs){let d=dueChild(c.id,m),p=paidChild(c.id,m);if(d>p)arrears.push({c,missing:d-p})}$("#arrearsList").innerHTML=arrears.map(x=>`<div class=arrearRow><span><b>${esc(x.c.lastName)} ${esc(x.c.firstName)}</b><br><small>${esc(x.c.parent||"")}</small></span><strong class=statusText unpaid>${money(x.missing)}</strong></div>`).join("")||'<div class=meta>Brak zaległości.</div>'}
function enrollmentHtml(e,m=$("#dashMonth").value){let st=status(e,m);return `<div class=enrollment><div class=itemTop><div><b>${esc(e.workshop)}</b><div class=meta>${esc(e.day)} ${esc(e.time)} • ${esc(e.school)}<br>Cena regularna ${money(e.regularPrice)} → <span class=price>${money(price(e))}</span>${e.discountMode!=="none"&&e.billingStatus==="Płatne"?` • rabat ${e.discountMode==="custom"?e.customDiscount:e.discountMode}%`:""}${e.priceNote?` • ${esc(e.priceNote)}`:""}</div></div><span class="statusText ${st==="paid"?"paid":st==="free"?"free":"unpaid"}">${statusLabel(e,m)}</span></div><button class="ghost mini editEnrollment" data-id="${e.id}">Edytuj zajęcia</button></div>`}
function childHtml(c){let m=$("#dashMonth").value,d=dueChild(c.id,m),p=paidChild(c.id,m);return `<div class=item><div class=itemTop><div><h4>${esc(c.lastName)} ${esc(c.firstName)}</h4><div class=meta>${esc(c.className)} • ${esc(c.school)} • świetlica: ${esc(c.club)} • ${esc(c.gender)}${(c.activeStatus||"Aktywny")!=="Aktywny"?` • NIEAKTYWNY`:""}</div><div class=meta><b>Do zapłaty ${esc(m)}: ${money(d)}</b> • wpłacono ${money(p)}</div></div><div><button class="ghost mini historyChild" data-id="${c.id}">Historia</button><button class="ghost mini editChild" data-id="${c.id}">Edytuj</button></div></div><div class=enrollments>${childEnrollments(c.id).map(enrollmentHtml).join("")||'<div class=meta>Brak przypisanych zajęć.</div>'}</div><button class="primary mini addEnrollment" data-child="${c.id}">+ Dodaj zajęcia</button></div>`}
function bindChildButtons(){ $$(".editChild").forEach(b=>b.onclick=()=>openChild(b.dataset.id));$$(".addEnrollment").forEach(b=>b.onclick=()=>openEnrollment(null,b.dataset.child));$$(".editEnrollment").forEach(b=>b.onclick=()=>openEnrollment(b.dataset.id));$$(".historyChild").forEach(b=>b.onclick=()=>openHistory(b.dataset.id))}
function renderChildren(){let q=$("#childSearch").value.toLowerCase(),s=$("#childSchool").value;let a=db.children.filter(c=>(c.lastName+" "+c.firstName).toLowerCase().includes(q)&&(!s||c.school===s)).sort((a,b)=>a.lastName.localeCompare(b.lastName,"pl"));$("#childrenList").innerHTML=a.map(childHtml).join("")||"<div class=item>Brak wyników.</div>";bindChildButtons()}
function renderPayments(){let m=$("#paymentMonth").value,q=$("#paymentSearch").value.toLowerCase();let html="";db.children.filter(c=>(c.lastName+" "+c.firstName+" "+c.parent).toLowerCase().includes(q)).sort((a,b)=>a.lastName.localeCompare(b.lastName,"pl")).forEach(c=>{let es=childEnrollments(c.id);html+=`<div class=item><h4>${esc(c.lastName)} ${esc(c.firstName)}</h4><div class=meta><b>Łącznie należne: ${money(dueChild(c.id,m))}</b> • wpłacono ${money(paidChild(c.id,m))}</div>${es.map(e=>{let st=status(e,m);return `<div class=enrollment><div class=itemTop><div><b>${esc(e.workshop)}</b><div class=meta>Należne ${money(price(e))} • wpłaty ${money(paid(e.id,m))}</div></div><span class="statusText ${st==="paid"?"paid":st==="free"?"free":"unpaid"}">${statusLabel(e,m)}</span></div><button class="ghost mini manualStatus" data-child="${c.id}" data-e="${e.id}" data-m="${m}">Korekta statusu</button>${db.payments.filter(p=>p.enrollmentId===e.id&&p.month===m).map(p=>`<button class="ghost mini editPayment" data-id="${p.id}">Edytuj ${money(p.amount)}</button><button class="danger mini deletePayment" data-id="${p.id}">Usuń</button>`).join("")}</div>`}).join("")}</div>`});$("#paymentsList").innerHTML=html||"<div class=item>Brak wyników.</div>";$$(".manualStatus").forEach(b=>b.onclick=()=>openManual(b.dataset.child,b.dataset.e,b.dataset.m));$$(".editPayment").forEach(b=>b.onclick=()=>openPayment(b.dataset.id));$$(".deletePayment").forEach(b=>b.onclick=()=>{if(confirm("Usunąć tę wpłatę?")){db.payments=db.payments.filter(p=>p.id!==b.dataset.id);save()}})}
function renderIncome(){let m=$("#incomeMonth").value,cat=$("#incomeCategory").value,a=db.incomes.filter(i=>i.month===m&&(!cat||i.category===cat));$("#incomeList").innerHTML=a.map(i=>`<div class=item><div class=itemTop><div><h4>${money(i.amount)} • ${esc(i.category)}</h4><div class=meta>${esc(i.date)} • ${esc(i.description)}${i.notes?` • ${esc(i.notes)}`:""}</div></div><div><button class="ghost mini editIncome" data-id="${i.id}">Edytuj</button><button class="danger mini deleteIncome" data-id="${i.id}">Usuń</button></div></div></div>`).join("")||"<div class=item>Brak dodatkowych przychodów.</div>";$$(".editIncome").forEach(b=>b.onclick=()=>openIncome(b.dataset.id));$$(".deleteIncome").forEach(b=>b.onclick=()=>{if(confirm("Usunąć przychód?")){db.incomes=db.incomes.filter(i=>i.id!==b.dataset.id);save()}})}
function groupRows(){let s=$("#groupSchool").value,d=$("#groupDay").value,t=$("#groupTime").value;return db.enrollments.filter(e=>(!s||e.school===s)&&(!d||e.day===d)&&(!t||e.time===t)).map(e=>({e,c:db.children.find(c=>c.id===e.childId)})).filter(x=>x.c&&(x.c.activeStatus||"Aktywny")==="Aktywny").sort((a,b)=>a.c.lastName.localeCompare(b.c.lastName,"pl"))}
function attKey(eid){return `${new Date().toISOString().slice(0,10)}|${eid}`}
function attendanceFor(eid){return db.attendance.find(a=>a.key===attKey(eid))}
function setAttendance(eid,val){db.attendance=db.attendance.filter(a=>a.key!==attKey(eid));db.attendance.push({key:attKey(eid),enrollmentId:eid,date:new Date().toISOString().slice(0,10),status:val});save()}
function renderGroups(){let rows=groupRows();$("#groupsList").innerHTML=rows.map(({c,e})=>{let a=attendanceFor(e.id);return `<div class=item><div class="screenOnly"><h4>${esc(c.lastName)} ${esc(c.firstName)}</h4><div class=meta>${esc(c.className)} • świetlica: ${esc(c.club)} • ${esc(e.workshop)} • ${esc(e.day)} ${esc(e.time)} • ${esc(e.school)}</div><div class=attendance><button class="ghost mini attYes ${a?.status==="Obecny"?"activeYes":""}" data-e="${e.id}">✓ Obecny</button><button class="ghost mini attNo ${a?.status==="Nieobecny"?"activeNo":""}" data-e="${e.id}">✕ Nieobecny</button></div></div><div class=printRow style="display:none"><span>${esc(c.lastName)}</span><span>${esc(c.firstName)}</span><span>${esc(c.className)}</span><span>${esc(c.club)}</span><span>${esc(e.workshop)}</span><span>${esc(e.day)}</span><span>${esc(e.time)}</span><span>${esc(e.school)}</span></div></div>`}).join("")||"<div class=item>Brak osób dla filtrów.</div>";$("#printHeader").innerHTML=`<h2>Lista uczestników</h2><p>${esc($("#groupSchool").value||"Wszystkie szkoły")} • ${esc($("#groupDay").value||"wszystkie dni")} • ${esc($("#groupTime").value||"wszystkie godziny")} • liczba: ${rows.length}</p><div class=printRow><b>Nazwisko</b><b>Imię</b><b>Klasa</b><b>Świetlica</b><b>Rodzaj zajęć</b><b>Dzień</b><b>Godzina</b><b>Szkoła</b></div>`;$$(".attYes").forEach(b=>b.onclick=()=>setAttendance(b.dataset.e,"Obecny"));$$(".attNo").forEach(b=>b.onclick=()=>setAttendance(b.dataset.e,"Nieobecny"))}
function renderReports(){let rows=MONTHS.map(m=>{let due=db.enrollments.reduce((s,e)=>s+(status(e,m)==="free"?0:price(e)),0),p=db.payments.filter(x=>x.month===m).reduce((s,x)=>s+Number(x.amount||0),0),i=db.incomes.filter(x=>x.month===m).reduce((s,x)=>s+Number(x.amount||0),0);return [m,due,p,Math.max(0,due-p),i,p+i]});$("#yearReport").innerHTML=`<table class=table><tr><th>Miesiąc</th><th>Należne</th><th>Wpłaty dzieci</th><th>Zaległe</th><th>Dodatkowe</th><th>Wpływy razem</th></tr>${rows.map(r=>`<tr><td>${r[0]}</td><td>${money(r[1])}</td><td>${money(r[2])}</td><td>${money(r[3])}</td><td>${money(r[4])}</td><td><b>${money(r[5])}</b></td></tr>`).join("")}</table>`;let wr={};db.enrollments.forEach(e=>wr[e.workshop]=(wr[e.workshop]||0)+1);$("#workshopReport").innerHTML=`<table class=table>${Object.entries(wr).map(([k,v])=>`<tr><td>${esc(k)}</td><th>${v}</th></tr>`).join("")}</table>`}
const settingNames={schools:"Szkoły",workshops:"Rodzaje zajęć",classes:"Klasy",clubs:"Świetlica",genders:"Płeć",days:"Dni",times:"Godziny",incomeCategories:"Kategorie dodatkowych przychodów"};
function renderSettings(){$("#settingsLists").innerHTML=Object.entries(settingNames).map(([k,n])=>`<div class=settingBox><h3>${n}</h3><div class=settingTags>${db.settings[k].map((x,i)=>`<span class=settingTag>${esc(x)} <button class="danger mini delSetting" data-key="${k}" data-i="${i}">×</button></span>`).join("")}</div><div class=addSetting><input data-new="${k}" placeholder="Dodaj nową pozycję"><button class="primary addSettingBtn" data-key="${k}">Dodaj</button></div></div>`).join("");$$(".addSettingBtn").forEach(b=>b.onclick=()=>{let i=$(`[data-new="${b.dataset.key}"]`),v=i.value.trim();if(v&&!db.settings[b.dataset.key].includes(v)){db.settings[b.dataset.key].push(v);i.value="";save()}});$$(".delSetting").forEach(b=>b.onclick=()=>{if(confirm("Usunąć pozycję z listy?")){db.settings[b.dataset.key].splice(+b.dataset.i,1);save()}})}
function renderApplications(){$("#applicationsList").innerHTML=db.applications.length?db.applications.map(a=>`<div class=match><b>${esc(a.name)}</b> • ${esc(a.school)} • ${esc(a.workshop)}<br><span class=badge>${esc(a.status)}</span> <button class="ghost mini appStatus" data-id="${a.id}" data-status="Potwierdzone">Potwierdzone</button><button class="ghost mini appStatus" data-id="${a.id}" data-status="Aktywne">Aktywne</button><button class="ghost mini appStatus" data-id="${a.id}" data-status="Zrezygnowało">Zrezygnowało</button></div>`).join(""):'<div class=meta>Brak zgłoszeń.</div>';$$(".appStatus").forEach(b=>b.onclick=()=>{let a=db.applications.find(x=>x.id===b.dataset.id);if(a){a.status=b.dataset.status;save()}})}
function populatePayers(selected=""){let s=$("#childPayer");s.innerHTML='<option value="">Brak wspólnego płatnika</option>'+db.payers.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")+`<option value="__new__">+ Nowa rodzina / płatnik</option>`;s.value=selected||""}
function openChild(id){let c=db.children.find(x=>x.id===id)||{activeStatus:"Aktywny"};optionsFromSettings();populatePayers(c.payerId);let f=$("#childForm");[...f.elements].forEach(el=>{if(el.name&&el.name!=="payerId")el.value=c[el.name]||""});$("#childPayer").value=c.payerId||"";$("#childDialog").showModal()}
function openEnrollment(id,childId){optionsFromSettings();let e=db.enrollments.find(x=>x.id===id)||{childId,billingStatus:"Płatne",discountMode:"none"};let f=$("#enrollmentForm");[...f.elements].forEach(el=>{if(el.name)el.value=e[el.name]??""});$("#enrollmentDialog").showModal()}
function populatePaymentChildren(q="",selected=""){let list=db.children.filter(c=>(c.lastName+" "+c.firstName).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>a.lastName.localeCompare(b.lastName,"pl"));$("#paymentChild").innerHTML=list.map(c=>`<option value="${c.id}">${esc(c.lastName)} ${esc(c.firstName)}</option>`).join("");if(selected)$("#paymentChild").value=selected;populatePaymentEnrollments()}
function populatePaymentEnrollments(selected=""){let id=$("#paymentChild").value;$("#paymentEnrollment").innerHTML=childEnrollments(id).map(e=>`<option value="${e.id}">${esc(e.workshop)} • ${esc(e.day)} ${esc(e.time)} • ${money(price(e))}</option>`).join("");if(selected)$("#paymentEnrollment").value=selected}
function openPayment(id){let p=db.payments.find(x=>x.id===id)||{month:$("#paymentMonth").value,date:new Date().toISOString().slice(0,10)};$("#paymentForm").reset();$("#paymentForm [name=id]").value=p.id||"";$("#paymentChildSearch").value="";populatePaymentChildren("",p.childId);if(p.childId){$("#paymentChild").value=p.childId;populatePaymentEnrollments(p.enrollmentId)}$("#paymentDialogMonth").value=p.month||$("#paymentMonth").value;$("#paymentForm [name=amount]").value=p.amount||"";$("#paymentForm [name=date]").value=p.date||"";$("#paymentForm [name=title]").value=p.title||"";$("#paymentDialog").showModal()}
function openManual(c,e,m){let x=manual(e,m)||{};let f=$("#manualStatusForm");f.childId.value=c;f.enrollmentId.value=e;f.month.value=m;f.status.value=x.status||"";f.note.value=x.note||"";$("#manualStatusDialog").showModal()}
function openIncome(id){optionsFromSettings();let x=db.incomes.find(i=>i.id===id)||{month:$("#incomeMonth").value,date:new Date().toISOString().slice(0,10)};let f=$("#incomeForm");[...f.elements].forEach(el=>{if(el.name)el.value=x[el.name]??""});$("#incomeDialog").showModal()}
function openHistory(id){let c=db.children.find(x=>x.id===id),es=childEnrollments(id);let html=`<h3>Historia: ${esc(c.lastName)} ${esc(c.firstName)}</h3>`;html+=es.map(e=>`<div class=enrollment><b>${esc(e.workshop)}</b><div class=meta>${esc(e.day)} ${esc(e.time)} • cena ${money(price(e))}</div><table class=table>${MONTHS.map(m=>`<tr><td>${m}</td><td>${money(paid(e.id,m))}</td><td><span class="statusText ${status(e,m)==="paid"?"paid":status(e,m)==="free"?"free":"unpaid"}">${statusLabel(e,m)}</span></td></tr>`).join("")}</table></div>`).join("");$("#historyContent").innerHTML=html;$("#historyDialog").showModal()}
$("#saveChild").onclick=e=>{e.preventDefault();let o=Object.fromEntries(new FormData($("#childForm")));if(!o.lastName||!o.firstName)return alert("Podaj nazwisko i imię.");if(o.payerId==="__new__"){let n=prompt("Nazwa rodziny / płatnika, np. Rodzina Kowalskich");if(n){let id="r"+Date.now();db.payers.push({id,name:n,parent:o.parent,phone:o.phone,email:o.email});o.payerId=id}else o.payerId=""}if(o.id)Object.assign(db.children.find(x=>x.id===o.id),o);else{o.id="c"+Date.now();db.children.push(o)}save();$("#childDialog").close()}
$("#saveEnrollment").onclick=e=>{e.preventDefault();let o=Object.fromEntries(new FormData($("#enrollmentForm")));o.regularPrice=Number(o.regularPrice||0);o.customPrice=Number(o.customPrice||0);o.customDiscount=Number(o.customDiscount||0);if(o.id)Object.assign(db.enrollments.find(x=>x.id===o.id),o);else{o.id="e"+Date.now();db.enrollments.push(o)}save();$("#enrollmentDialog").close()}
$("#savePayment").onclick=e=>{e.preventDefault();let o=Object.fromEntries(new FormData($("#paymentForm")));o.amount=Number(o.amount||0);if(o.id)Object.assign(db.payments.find(x=>x.id===o.id),o);else{o.id="p"+Date.now();db.payments.push(o)}save();$("#paymentDialog").close()}
$("#saveManualStatus").onclick=e=>{e.preventDefault();let o=Object.fromEntries(new FormData($("#manualStatusForm")));db.manualStatuses=db.manualStatuses.filter(x=>!(x.enrollmentId===o.enrollmentId&&x.month===o.month));if(o.status)db.manualStatuses.push({...o,id:"m"+Date.now()});save();$("#manualStatusDialog").close()}
$("#saveIncome").onclick=e=>{e.preventDefault();let o=Object.fromEntries(new FormData($("#incomeForm")));o.amount=Number(o.amount||0);if(o.id)Object.assign(db.incomes.find(x=>x.id===o.id),o);else{o.id="i"+Date.now();db.incomes.push(o)}save();$("#incomeDialog").close()}
$("#addChildBtn").onclick=()=>openChild();$("#addPaymentBtn").onclick=()=>openPayment();$("#addIncomeBtn").onclick=()=>openIncome();
$("#paymentChildSearch").oninput=e=>populatePaymentChildren(e.target.value);$("#paymentChild").onchange=()=>populatePaymentEnrollments();
$("#quickSearch").oninput=e=>{let q=e.target.value.trim().toLowerCase();$("#quickResults").innerHTML=q?db.children.filter(c=>c.lastName.toLowerCase().startsWith(q)).slice(0,8).map(c=>`<div class=item><b>${esc(c.lastName)} ${esc(c.firstName)}</b><div class=meta>${esc(c.className)} • ${esc(c.school)} • zajęcia: ${childEnrollments(c.id).length}</div></div>`).join(""):""}
$("#childSearch").oninput=renderChildren;$("#childSchool").onchange=renderChildren;$("#paymentSearch").oninput=renderPayments;$("#paymentMonth").onchange=renderPayments;$("#incomeMonth").onchange=renderIncome;$("#incomeCategory").onchange=renderIncome;$("#dashMonth").onchange=renderDashboard;$("#dashSchool").onchange=renderDashboard;["groupSchool","groupDay","groupTime"].forEach(id=>$("#"+id).onchange=renderGroups);$("#printGroup").onclick=()=>print();
$("#copyReminderBtn").onclick=async()=>{let m=$("#dashMonth").value,lines=[];for(const c of db.children){let miss=dueChild(c.id,m)-paidChild(c.id,m);if(miss>0)lines.push(`${c.lastName} ${c.firstName}: ${money(miss)}`)}let text=`Zaległości za ${m}:\n`+lines.join("\n");try{await navigator.clipboard.writeText(text);alert("Skopiowano listę zaległości.")}catch{prompt("Skopiuj tekst:",text)}}
$("#analyzeBank").onclick=()=>{let lines=$("#bankPaste").value.split(/\n+/).filter(Boolean);$("#bankPreview").innerHTML=lines.map((l,i)=>{let matches=db.children.filter(c=>l.toLowerCase().includes(c.lastName.toLowerCase())||l.toLowerCase().includes(c.firstName.toLowerCase()));let amount=(l.match(/(\d{2,4}[,.]\d{2})/)||[])[1];let best=matches[0];return `<div class=match>${esc(l)}<br><b>${matches.length?"Możliwe: "+matches.map(c=>esc(c.lastName+" "+c.firstName)).join(", "):"Brak pewnego dopasowania"}</b>${amount?` • ${amount} zł`:""}${best&&amount?` <button class="primary mini bankAccept" data-child="${best.id}" data-amount="${amount.replace(",",".")}">Zaksięguj ręcznie</button>`:""}</div>`}).join("");$$(".bankAccept").forEach(b=>b.onclick=()=>{openPayment();$("#paymentChild").value=b.dataset.child;populatePaymentEnrollments();$("#paymentForm [name=amount]").value=b.dataset.amount})}
function parseCSV(t){let rows=[],r=[],c="",q=false;for(let i=0;i<t.length;i++){let x=t[i],n=t[i+1];if(x=='"'&&q&&n=='"'){c+='"';i++}else if(x=='"')q=!q;else if(x==","&&!q){r.push(c);c=""}else if((x=="\n"||x=="\r")&&!q){if(x=="\r"&&n=="\n")i++;r.push(c);c="";if(r.some(v=>v))rows.push(r);r=[]}else c+=x}if(c||r.length){r.push(c);rows.push(r)}return rows}
$("#parseForm").onclick=()=>{let rows=parseCSV($("#formPaste").value.trim());if(rows.length<2)return alert("Brak danych.");let h=rows[0].map(x=>x.toLowerCase()),idx=s=>h.findIndex(x=>x.startsWith(s)),all=s=>h.map((x,i)=>x.startsWith(s)?i:-1).filter(i=>i>=0);let parsed=rows.slice(1).map(r=>{let full=r[idx("imię i nazwisko dziecka")]||"",p=full.trim().split(/\s+/),first=p.shift()||"",last=p.join(" "),wi=all("rodzaj zajęć"),di=all("które dni");return{first,last,school:r[idx("szkoła")]||"",className:r[idx("klasa")]||"",workshop:r[wi[0]]||r[wi[1]]||"",day:r[di[0]]||r[di[1]]||"",parent:r[idx("imię i nazwisko rodzica")]||"",phone:r[idx("numer telefonu")]||"",email:r[idx("adres e-mail")]||""}});$("#formPreview").innerHTML=parsed.map((x,i)=>`<div class=match><b>${esc(x.last)} ${esc(x.first)}</b> • ${esc(x.school)} • ${esc(x.workshop)} <button class="primary importForm" data-i="${i}">Dodaj jako nowe zgłoszenie</button></div>`).join("");$$(".importForm").forEach(b=>b.onclick=()=>{let x=parsed[+b.dataset.i],id="a"+Date.now()+Math.random();db.applications.push({id,name:`${x.last} ${x.first}`,school:x.school,className:x.className,workshop:x.workshop,day:x.day,parent:x.parent,phone:x.phone,email:x.email,status:"Nowe zgłoszenie"});save();b.disabled=true;b.textContent="Dodano"})}
function download(n,t,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("#backupBtn").onclick=$("#exportJson").onclick=()=>download("rozliczenia-kopia-v4.json",JSON.stringify(db,null,2),"application/json");
$("#exportCsv").onclick=()=>{let head=["Nazwisko","Imię","Klasa","Świetlica","Rodzaj zajęć","Dzień","Godzina","Szkoła","Status","Cena",...MONTHS];let rows=db.enrollments.map(e=>{let c=db.children.find(x=>x.id===e.childId);return[c.lastName,c.firstName,c.className,c.club,e.workshop,e.day,e.time,e.school,e.billingStatus,price(e),...MONTHS.map(m=>paid(e.id,m))]});download("rozliczenia-v4.csv",[head,...rows].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv;charset=utf-8")}
$("#restoreJson").onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(!x.children||!x.enrollments)throw 0;if(confirm("Przywrócić kopię i zastąpić obecne dane?")){db=x;for(const k of ["payers","attendance","applications"])if(!db[k])db[k]=[];save()}}catch{alert("Nieprawidłowa kopia.")}}
$$("[data-go]").forEach(b=>b.onclick=()=>{$$(".view").forEach(v=>v.classList.toggle("active",v.dataset.view===b.dataset.go));$$("[data-go]").forEach(x=>x.classList.toggle("active",x===b));scrollTo(0,0)})
fillMonths();render();