const MONTHS=["Wrzesień","Październik","Listopad","Grudzień","Styczeń","Luty","Marzec","Kwiecień","Maj","Czerwiec","Lipiec","Sierpień"];
const KEY="rw_v2_data";
const demo={children:[
{id:"c1",lastName:"Kolasa",firstName:"Nikola",gender:"Dziewczynka",school:"SP162",className:"4A",club:"tak",workshop:"zaawansowane",day:"wtorek",time:"15:00",parent:"Łukasz Kolasa",phone:"50340488",email:"mexilianpl@gmail.com",notes:""},
{id:"c2",lastName:"Nowak",firstName:"Maja",gender:"Dziewczynka",school:"SP162",className:"3B",club:"tak",workshop:"rękodzieło",day:"środa",time:"14:30",parent:"Anna Nowak",phone:"",email:"",notes:""},
{id:"c3",lastName:"Kowalski",firstName:"Jan",gender:"Chłopiec",school:"ZSP17",className:"5A",club:"nie",workshop:"zaawansowane",day:"wtorek",time:"15:00",parent:"Piotr Kowalski",phone:"",email:"",notes:""}],
payments:[
{id:"p1",childId:"c1",month:"Wrzesień",amount:155,date:"2026-09-03",title:"Nikola"},
{id:"p2",childId:"c2",month:"Wrzesień",amount:165,date:"2026-09-04",title:"Maja"},
{id:"p3",childId:"c3",month:"Wrzesień",amount:155,date:"2026-09-05",title:"Jan"},
{id:"p4",childId:"c1",month:"Październik",amount:155,date:"2026-09-03",title:"nadpłata na kolejny miesiąc"}]};
let db=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(demo)}catch(e){return structuredClone(demo)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function money(n){return Number(n||0).toLocaleString("pl-PL",{style:"currency",currency:"PLN"})}
function fillMonths(){["month","paymentMonth"].forEach(id=>{$("#"+id).innerHTML=MONTHS.map(m=>`<option>${m}</option>`).join("")}); $("#paymentForm select[name=month]").innerHTML=MONTHS.map(m=>`<option>${m}</option>`).join("")}
function paidFor(id,m){return db.payments.filter(p=>p.childId===id&&p.month===m).reduce((a,p)=>a+Number(p.amount||0),0)}
function render(){
 const m=$("#month").value||"Wrzesień"; const total=db.payments.filter(p=>p.month===m).reduce((a,p)=>a+Number(p.amount||0),0);
 $("#sChildren").textContent=db.children.length; $("#sGirls").textContent=db.children.filter(x=>x.gender==="Dziewczynka").length; $("#sBoys").textContent=db.children.filter(x=>x.gender==="Chłopiec").length;
 $("#sPaid").textContent=money(total); $("#sUnpaid").textContent=db.children.filter(c=>paidFor(c.id,m)<=0).length;
 $("#sGroups").textContent=new Set(db.children.map(c=>[c.day,c.time,c.workshop,c.school].join("|"))).size;
 $("#monthSummary").innerHTML=`<b>${esc(m)}</b>: ${money(total)} • zapłaciło ${db.children.filter(c=>paidFor(c.id,m)>0).length}/${db.children.length}`;
 renderChildren(); renderPayments(); renderGroups(); renderReport(); refreshFilters();
}
function childCard(c,m=$("#month").value){const p=paidFor(c.id,m);return `<div class="item"><div class="itemTop"><div><b>${esc(c.lastName)} ${esc(c.firstName)}</b><div class="meta">${esc(c.className)} • ${esc(c.school)} • ${esc(c.workshop)}</div></div><span class="${p>0?"paid":"unpaid"}">${p>0?money(p):"brak"}</span></div><div class="meta extra">${esc(c.day)} ${esc(c.time)} • świetlica: ${esc(c.club||"—")} • ${esc(c.parent||"")}</div><button class="ghost editChild" data-id="${c.id}">Edytuj</button></div>`}
function renderChildren(){let q=$("#childSearch").value.toLowerCase(),sf=$("#schoolFilter").value,cf=$("#classFilter").value;let a=db.children.filter(c=>(Object.values(c).join(" ").toLowerCase().includes(q))&&(!sf||c.school===sf)&&(!cf||c.className===cf));$("#childrenList").innerHTML=a.sort((a,b)=>a.lastName.localeCompare(b.lastName,"pl")).map(c=>childCard(c)).join("")||"<div class=item>Brak wyników.</div>"; $$(".editChild").forEach(b=>b.onclick=()=>openChild(b.dataset.id))}
function renderPayments(){let m=$("#paymentMonth").value||"Wrzesień",q=$("#paymentSearch").value.toLowerCase();let rows=db.children.filter(c=>(c.lastName+" "+c.firstName+" "+c.parent).toLowerCase().includes(q)).sort((a,b)=>a.lastName.localeCompare(b.lastName,"pl"));$("#paymentsList").innerHTML=rows.map(c=>childCard(c,m)).join("")}
function renderGroups(){let d=$("#dayFilter").value,t=$("#timeFilter").value;let a=db.children.filter(c=>(!d||c.day===d)&&(!t||c.time===t));$("#groupsList").innerHTML=a.sort((a,b)=>(a.day+a.time+a.lastName).localeCompare(b.day+b.time+b.lastName,"pl")).map(c=>`<div class=item><b>${esc(c.lastName)} ${esc(c.firstName)}</b><div class=meta>${esc(c.className)} • świetlica: ${esc(c.club||"—")} • ${esc(c.workshop)} • ${esc(c.day)} ${esc(c.time)} • ${esc(c.school)}</div></div>`).join("")||"<div class=item>Brak osób.</div>"}
function renderReport(){let h=`<table class=table><tr><th>Miesiąc</th><th>Wpłaty</th><th>Osoby</th><th>Braki</th></tr>`;MONTHS.forEach(m=>{let sum=db.payments.filter(p=>p.month===m).reduce((a,p)=>a+Number(p.amount||0),0),n=db.children.filter(c=>paidFor(c.id,m)>0).length;h+=`<tr><td>${m}</td><td>${money(sum)}</td><td>${n}</td><td>${db.children.length-n}</td></tr>`});$("#yearReport").innerHTML=h+"</table>"}
function refreshFilters(){let keep=(sel,vals,label)=>{let v=sel.value;sel.innerHTML=`<option value="">${label}</option>`+[...new Set(vals.filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join("");sel.value=v};keep($("#schoolFilter"),db.children.map(c=>c.school),"Wszystkie szkoły");keep($("#classFilter"),db.children.map(c=>c.className),"Wszystkie klasy");keep($("#dayFilter"),db.children.map(c=>c.day),"Dzień");keep($("#timeFilter"),db.children.map(c=>c.time),"Godzina")}
function openChild(id){let c=db.children.find(x=>x.id===id)||{};let f=$("#childForm");[...f.elements].forEach(el=>{if(el.name)el.value=c[el.name]||""});$("#childDialog").showModal()}
$("#saveChildBtn").onclick=e=>{e.preventDefault();let f=new FormData($("#childForm")),o=Object.fromEntries(f);if(!o.lastName||!o.firstName)return alert("Podaj nazwisko i imię.");if(o.id){Object.assign(db.children.find(c=>c.id===o.id),o)}else{o.id="c"+Date.now();db.children.push(o)}save();$("#childDialog").close()}
$("#addChildBtn").onclick=()=>openChild();
$("#addPaymentBtn").onclick=()=>{let s=$("#paymentForm select[name=childId]");s.innerHTML=db.children.sort((a,b)=>a.lastName.localeCompare(b.lastName,"pl")).map(c=>`<option value="${c.id}">${esc(c.lastName)} ${esc(c.firstName)}</option>`).join("");$("#paymentForm select[name=month]").value=$("#paymentMonth").value;$("#paymentDialog").showModal()}
$("#savePaymentBtn").onclick=e=>{e.preventDefault();let o=Object.fromEntries(new FormData($("#paymentForm")));if(!o.childId||!o.amount)return;db.payments.push({...o,id:"p"+Date.now(),amount:Number(o.amount)});save();$("#paymentDialog").close();$("#paymentForm").reset()}
function parseCSV(text){let rows=[],row=[],cell="",q=false;for(let i=0;i<text.length;i++){let ch=text[i],n=text[i+1];if(ch=='"'&&q&&n=='"'){cell+='"';i++}else if(ch=='"'){q=!q}else if(ch==","&&!q){row.push(cell);cell=""}else if((ch=="\n"||ch=="\r")&&!q){if(ch=="\r"&&n=="\n")i++;row.push(cell);cell="";if(row.some(x=>x!==""))rows.push(row);row=[]}else cell+=ch}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function normalizeHeader(s){return s.toLowerCase().replace(/\s+/g," ").trim()}
$("#parseFormBtn").onclick=()=>{let rows=parseCSV($("#formPaste").value.trim());if(rows.length<2)return alert("Wklej nagłówki i dane.");let hdr=rows[0].map(normalizeHeader);let find=(r,starts,occ=0)=>{let ids=hdr.map((h,i)=>starts.some(s=>h.startsWith(s))?i:-1).filter(i=>i>=0);return r[ids[occ]??-1]||""};let parsed=rows.slice(1).map(r=>{let full=find(r,["imię i nazwisko dziecka"]);let parts=full.trim().split(/\s+/);return{firstName:parts.shift()||"",lastName:parts.join(" "),school:find(r,["szkoła"]),className:find(r,["klasa"]),workshop:find(r,["rodzaj zajęć"],0)||find(r,["rodzaj zajęć"],1),day:find(r,["które dni"],0)||find(r,["które dni"],1),parent:find(r,["imię i nazwisko rodzica"]),phone:find(r,["numer telefonu"]),email:find(r,["adres e-mail"]),notes:find(r,["uwagi"]),gender:"",club:"",time:""}});$("#formPreview").innerHTML=parsed.map((c,i)=>`<div class=match><b>${esc(c.lastName)} ${esc(c.firstName)}</b> • ${esc(c.school)} ${esc(c.className)} • ${esc(c.workshop)} • ${esc(c.day)} <button class=primary data-import="${i}">Dodaj</button></div>`).join("");$$("[data-import]").forEach(b=>b.onclick=()=>{let c=parsed[+b.dataset.import];let dup=db.children.find(x=>x.firstName.toLowerCase()==c.firstName.toLowerCase()&&x.lastName.toLowerCase()==c.lastName.toLowerCase()&&x.school.toLowerCase()==c.school.toLowerCase());if(dup&&!confirm("Podobne dziecko już istnieje. Dodać mimo to?"))return;c.id="c"+Date.now()+Math.random();db.children.push(c);save();b.disabled=true;b.textContent="Dodano"})}
$("#parseBankBtn").onclick=()=>{let text=$("#bankPaste").value;let lines=text.split(/\n+/).filter(Boolean);let html="";lines.forEach((line,i)=>{let lower=line.toLowerCase(),matches=db.children.filter(c=>lower.includes(c.lastName.toLowerCase())||lower.includes(c.firstName.toLowerCase()));let amt=(line.match(/(\d{2,4}[,.]\d{2})\s*(?:pln|zł)?/i)||[])[1];html+=`<div class=match><div>${esc(line.slice(0,180))}</div><b>${matches.length?`Możliwe: ${matches.map(c=>esc(c.lastName+" "+c.firstName)).join(", ")}`:"Brak pewnego dopasowania"}</b>${amt?` • ${amt} zł`:""}</div>`});$("#bankPreview").innerHTML=html||"Brak danych."}
$("#quickSearch").oninput=e=>{let q=e.target.value.trim().toLowerCase();$("#quickResults").innerHTML=q?db.children.filter(c=>c.lastName.toLowerCase().startsWith(q)).slice(0,8).map(c=>childCard(c)).join(""):""}
$("#childSearch").oninput=renderChildren;$("#paymentSearch").oninput=renderPayments;$("#schoolFilter").onchange=renderChildren;$("#classFilter").onchange=renderChildren;$("#paymentMonth").onchange=renderPayments;$("#month").onchange=render;$("#dayFilter").onchange=renderGroups;$("#timeFilter").onchange=renderGroups;
$$("[data-go]").forEach(b=>b.onclick=()=>{$$(".view").forEach(v=>v.classList.toggle("active",v.dataset.view===b.dataset.go));$$("[data-go]").forEach(x=>x.classList.toggle("active",x===b));scrollTo(0,0)})
$("#printGroupBtn").onclick=()=>print();
function download(name,text,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$("#exportJsonBtn").onclick=$("#backupBtn").onclick=()=>download("rozliczenia-kopia.json",JSON.stringify(db,null,2),"application/json");
$("#exportCsvBtn").onclick=()=>{let h=["Nazwisko","Imię","Klasa","Świetlica","Rodzaj zajęć","Dzień","Godzina","Szkoła",...MONTHS];let rows=db.children.map(c=>[c.lastName,c.firstName,c.className,c.club,c.workshop,c.day,c.time,c.school,...MONTHS.map(m=>paidFor(c.id,m))]);download("rozliczenia.csv",[h,...rows].map(r=>r.map(x=>`"${String(x??"").replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv;charset=utf-8")}
$("#restoreInput").onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(!x.children||!x.payments)throw 0;if(confirm("Zastąpić bieżące dane kopią?")){db=x;save()}}catch{alert("Nieprawidłowy plik kopii.")}}
fillMonths();$("#paymentMonth").value="Wrzesień";render();