(function(){
"use strict";
function esc91(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function norm91(s){return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\s+/g," ").trim()}
function month91(){if(typeof currentMonthName==="function")return currentMonthName();const a=["Styczeń","Luty","Marzec","Kwiecień","Maj","Czerwiec","Lipiec","Sierpień","Wrzesień","Październik","Listopad","Grudzień"];return a[new Date().getMonth()]}
function date91(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function children91(){return (data.children||[]).filter(c=>typeof childActiveNow==="function"?childActiveNow(c):true).slice().sort((a,b)=>`${a.last} ${a.first}`.localeCompare(`${b.last} ${b.first}`,"pl"))}
function state91(ch,m){try{return paymentState(ch,m)}catch(e){const due=typeof childDue==="function"?childDue(ch):0;const paid=typeof childPaymentsForMonth==="function"?childPaymentsForMonth(ch,m):0;return{due,paid,missing:Math.max(0,due-paid)}}}
window.pay91Search=function(v){const box=document.getElementById("pay91Results");if(!box)return;const q=norm91(v);if(!q){box.innerHTML="";return}const words=q.split(" ").filter(Boolean);const found=children91().filter(c=>{const hay=norm91([c.last,c.first,`${c.last} ${c.first}`,`${c.first} ${c.last}`,c.school||"",c.class||"",c.parent||"",c.phone||""].join(" "));return words.every(w=>hay.includes(w))}).slice(0,25);if(!found.length){box.innerHTML='<div class="pay91-empty">Brak pasującego dziecka.</div>';return}box.innerHTML=found.map(c=>`<button type="button" class="pay91-result" onclick="pay91Open(${c.id})"><span><b>${esc91(c.last)} ${esc91(c.first)}</b><small>${esc91(c.school||"")}${c.class?` • ${esc91(c.class)}`:""}</small></span><span class="pay91-arrow">›</span></button>`).join("")}
window.pay91Open=function(cid){const ch=(data.children||[]).find(c=>Number(c.id)===Number(cid));if(!ch)return;let m=month91();try{const p=JSON.parse(localStorage.getItem("rw91pay")||"{}");if((months||[]).includes(p.month))m=p.month}catch(e){}modal(`<div><h2>Dodaj wpłatę</h2><div class="pay91-selected">${esc91(ch.last)} ${esc91(ch.first)}${ch.school?` • ${esc91(ch.school)}`:""}${ch.class?` • ${esc91(ch.class)}`:""}</div><input id="pay91Child" type="hidden" value="${ch.id}"><label>Miesiąc</label><select id="pay91Month" onchange="pay91Refresh(true)">${(months||[]).map(x=>`<option ${x===m?"selected":""}>${x}</option>`).join("")}</select><div id="pay91Summary"></div><label>Kwota wpłaty</label><input id="pay91Amount" type="number" min="0" step="0.01" inputmode="decimal"><label>Data</label><input id="pay91Date" type="date" value="${date91()}"><div class="actions"><button class="soft" onclick="closeModal()">Anuluj</button><button class="primary" onclick="pay91Save()">Zapisz wpłatę</button></div></div>`);pay91Refresh(true)}
window.pay91Refresh=function(setAmount){const cid=Number(document.getElementById("pay91Child")?.value||0);const m=document.getElementById("pay91Month")?.value||month91();const ch=(data.children||[]).find(c=>Number(c.id)===cid);if(!ch)return;const ps=state91(ch,m);document.getElementById("pay91Summary").innerHTML=`<div class="pay91-summary"><div><span>Należne</span><b>${money(ps.due||0)}</b></div><div><span>Wpłacono</span><b>${money(ps.paid||0)}</b></div><div class="missing"><span>Brakuje</span><b>${money(ps.missing||0)}</b></div></div>`;const a=document.getElementById("pay91Amount");if(a&&setAmount)a.value=Number(ps.missing||0).toFixed(2);localStorage.setItem("rw91pay",JSON.stringify({month:m}))}
window.pay91Save=function(){const cid=Number(document.getElementById("pay91Child")?.value||0);const m=document.getElementById("pay91Month")?.value||month91();const amount=Number(String(document.getElementById("pay91Amount")?.value||"0").replace(",","."));const dt=document.getElementById("pay91Date")?.value||date91();const ch=(data.children||[]).find(c=>Number(c.id)===cid);if(!ch)return;if(!(amount>0)){if(typeof showToast==="function")showToast("Podaj kwotę większą od 0");return}data.payments.push({id:Date.now(),childId:ch.id,child:`${ch.last} ${ch.first}`,month:m,amount,date:dt,note:"Szybka wpłata"});if(typeof logHistory==="function")logHistory(ch.id,`Dodano wpłatę ${money(amount)} za ${m}.`);save();closeModal();page="payments";render();if(typeof showToast==="function")showToast("Wpłata zapisana")}
function apply91(){document.getElementById("quickPaymentStart89")?.remove();if(page!=="payments"||!app)return;const cards=[...app.querySelectorAll(".card")];const card=cards.find(x=>norm91(x.querySelector("h2")?.textContent)==="dodaj wplate");if(!card)return;card.innerHTML=`<h2>Dodaj wpłatę</h2><div class="search"><input id="pay91Input" autocomplete="off" placeholder="Szukaj dziecka..." oninput="pay91Search(this.value)"></div><div id="pay91Results" class="pay91-results"></div><div class="pay91-help">Wpisz pierwsze litery nazwiska lub imienia — lista dzieci pojawi się automatycznie.</div>`}
const oldPayments=window.payments;if(typeof oldPayments==="function")window.payments=function(){oldPayments();apply91()};const oldStart=window.start;if(typeof oldStart==="function")window.start=function(){oldStart();document.getElementById("quickPaymentStart89")?.remove()};setTimeout(apply91,0)
})();
